# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6828c64c9dafec142e8fc07e1e723b748eaf1d9aac9be1c46154557b0516c746d08e519878c393d4c5e76e76e4acda2b377a29dd2d20f16ba9c47e03035b9dba

test:
  secret_key_base: 02773135a50d97dfbc5df794c412404706f46d33f5ae5101bfd78f15ed12b25f0515a87cc3a0aadee7715c356d65013b5efe944efdd9f86a371e5db2039cce5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
